<pre>
<?php
	
	require('../lib/options.php');
	$file = fopen("../data/ips.txt", "r");
	$ips_list = fread($file, filesize("../data/ips.txt"));
	$ips_array = explode("\n",$ips_list);
	$ips_string = implode("\",\"", $ips_array);

	# We need to account for possible line breaks of '\n'. 	

?>


#############################################################
# IPs must be in format of "123.23.22.0/12", "123.12.2.0/10"
# ForeignBlacklist Firewall Rule Must be Set Already
#
# Due to the lack of wget in Powershell, this might
# need to be re-downloaded monthly
#############################################################
# Generated by GEO IP Block Tool: <?php echo date('F j, Y'); ?>
# Originally on: https://github.com/qneville/geoip-blocker

# <?php echo $options["url"]."/templates/blocklist.ps.php"; ?>

#############################################################

# Get List Of Blocked IP's
$IPs = @(
		<?php echo "\"".substr($ips_string,0,-2); ?>
) | `Foreach-object {
		netsh advfirewall firewall set rule name="ForeignBlacklist" new remoteip="$_"
		write-host "$_ Added $?"
}
</pre>