<pre>
<?php
	require('../lib/options.php');
?>

#############################################################
# Run this as a montly cron-job
#############################################################
# Originally adapted by Quintan Neville - May 4
# Originally on: https://github.com/qneville/geoip-blocker
# Generated by GEO IP Block Tool: <?php echo date('F j, Y'); ?>

#############################################################
# https://www.cyberciti.biz/faq/block-entier-country-using-iptables/
# This script was downloaded from: <?php echo $options["url"]."/templates/iptables.sh.php"; ?>

#############################################################
 
### Set PATH ###
IPT=/sbin/iptables
WGET=/usr/bin/wget
EGREP=/bin/egrep
 
### No editing below ###
SPAMLIST="countrydrop"
ZONEROOT="/root/iptables"
<?php
echo "DLROOT=\"".$options['url']."/ips.php\""
?>

cleanOldRules(){
  $IPT -F
  $IPT -X
  $IPT -t nat -F
  $IPT -t nat -X
  $IPT -t mangle -F
  $IPT -t mangle -X
  $IPT -P INPUT ACCEPT
  $IPT -P OUTPUT ACCEPT
  $IPT -P FORWARD ACCEPT
}
 
# create a dir
[ ! -d $ZONEROOT ] && /bin/mkdir -p $ZONEROOT
 
# clean old rules
cleanOldRules
 
# create a new iptables list
$IPT -N $SPAMLIST
 
# GET IPs from source

# local zone file
tDB=$ZONEROOT/regions.zone

# get fresh zone file
$WGET -O $tDB $DLROOT

# country specific log message
SPAMDROPMSG="All Regions Country Drop"

# get 
BADIPS=$(egrep -v "^#|^$" $tDB)
for ipblock in $BADIPS
do
   $IPT -A $SPAMLIST -s $ipblock -j LOG --log-prefix "$SPAMDROPMSG"
   $IPT -A $SPAMLIST -s $ipblock -j DROP
done

 
# Drop everything 
$IPT -I INPUT -j $SPAMLIST
$IPT -I OUTPUT -j $SPAMLIST
$IPT -I FORWARD -j $SPAMLIST
 
# call your other iptable script
# /path/to/other/iptables.sh
 
exit 0
</pre>